# Setup
title: 海苔脆的博客
description: 不改变世界也要给予挣扎
url: https://huatiancen.github.io
avatar: /avatar.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: Huatiancen
  card: summary
logo: logo.png
social:
  name: Tiancen Hua
  links:
    - https://twitter.com/Huatiancen
    - https://github.com/Huatiancen
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Giscus 评论系统配置（免费，基于 GitHub Discussions）
giscus:
  repo: "Huatiancen/Huatiancen.github.io"  # 你的仓库名
  repo_id: "R_kgDOOWtknA"  # 仓库 ID，从 giscus.app 获取
  category: "General"  # 讨论分类
  category_id: "DIC_kwDOOWtknM4Cr6xF"  # 分类 ID，从 giscus.app 获取

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus (如果不用 Giscus 的话)
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Tiancen Hua
  url: https://github.com/Huatiancen
  email: 1047347257@qq.com
  
remote_theme: vszhub/not-pure-poole